Update linters/formatters
I ran `pre-commit autoupdate` and then updated the pre-commit version and the required Python version to match.

The old version of black we are using here is failing with this error:

Traceback (most recent call last):
  File "/home/runner/.cache/pre-commit/repo07dyn8s4/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/runner/.cache/pre-commit/repo07dyn8s4/py_env-python3/lib/python3.9/site-packages/black.py", line 4134, in patched_main
    patch_click()
  File "/home/runner/.cache/pre-commit/repo07dyn8s4/py_env-python3/lib/python3.9/site-packages/black.py", line 4123, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/runner/.cache/pre-commit/repo07dyn8s4/py_env-python3/lib/python3.9/site-packages/click/__init__.py)

The lastest version fixes this error and also reformats some lines. The new version of the pre-commit hook needed a newer version of pre-commit so I had to update that in the lock file. The new version of pre-commit is incompatible with Python 3.6.0 so I dropped support for that.